### ISSUE TITLE
How to install the RFLinkGateway?

### ISSUE THREAD

**Issue by yanickvanbarneveld** [Iture/RFLinkGateway#6]
Hi,

How do I install the RFLinkGateway/MQTT Broker? I installed succesfully the firmware on my RFLink but now I need to connect it with OpenHab. I found out that I have to do somewithing with "Mosquitto" but I can not find out what...

Can someone please give me some instructions to help me further?

Kind regards,
Yanick

**Comment by yanickvanbarneveld** [comment]
I installed succesfully Mosquitto. Now I can send messages using:
`mosquitto_pub -h localhost -t "sensor/temperature" -m 22`

and retrieve messages using:
`mosquitto_sub -h localhost -t "sensor/temperature"`

But what I have todo now?

**Comment by Iture** [comment]
Hi
basically it's not an issue :)
You need to configure MQTT add-on in openhab - here you have a document for version 1: [https://github.com/openhab/openhab1-addons/wiki/MQTT-Binding](https://github.com/openhab/openhab1-addons/wiki/MQTT-Binding)
then you need to have some items bound to particular topics and messages according to this documentation. 
Here you have sample binding string for one of remote power sockets in my home:
`>[mosquitto:/data/RFLINK/TriState/85562a/W/1:command:OFF:OFF],>[mosquitto:/data/RFLINK/TriState/85562a/W/1:command:ON:ON]`
